env:
  browser: true
  es2021: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules: {}

# env:
#   browser: true
#   es2020: true
# extends:
#   - airbnb-base
# parserOptions:
#   ecmaVersion: 11
#   sourceType: module
# rules: {}
